
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxzaoupszacrtteiemgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94emFvdXBzemFjcnR0ZWllbWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MDE0OTgsImV4cCI6MjA1ODE3NzQ5OH0.chYn-BtDfU9UxE-X2scMTm-uLdz88mwqu6f68VZ-lRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
